name: coleta_certa
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.5.3
  http: ^1.1.0
  url_launcher: ^6.2.5
  google_maps_flutter: ^2.6.0
  flutter_dotenv: ^5.1.0
  sqflite: ^2.3.0
  path: ^1.9.0
  image_picker: ^1.0.4
  extended_image: ^8.2.0
  image: ^4.0.17
  flutter_html: ^3.0.0
  flutter_markdown: ^0.6.18
  geolocator: ^11.0.0
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/img/
    - .env
    - lib/assets/data/
    - lib/assets/html/
    - lib/assets/faq/data/
    - lib/assets/faq/html/
    - README.md

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/coleta_certa.png"